Unityやライブラリなどのサードパーティーのバージョンアップ
extreal-dev/Extreal.SampleApp.Holiday.P2P pull request #1
Opened 2024-02-09 10:05 UTC by sus-yoshikane-t

# 何の変更を加えましたか？

- Unityやライブラリなどのサードパーティーのバージョンアップをしました。
  - https://github.com/extreal-dev/Extreal.SampleApp.Holiday.P2P/commit/13dfbbc6a621ece1c634ce163fe1c65778b72deb
  - AppUsageのMinIOでcurlが使えなくなった関係でhealth checkのtestを更新しました。（AppUsage/docker-compose.yaml）
- WebGLで利用状況可視化を利用しようとするとCORSエラーが出ていたのを修正しました。
  - https://github.com/extreal-dev/Extreal.SampleApp.Holiday.P2P/commit/4b3efafc4607fabc9d189cc9d8c28e3b96dacc10
- 静的解析の警告を修正しました。
  - https://github.com/extreal-dev/Extreal.SampleApp.Holiday.P2P/commit/45b425fe888d37261971407d7182b6d2989fba13 (NetworkThirdPersonController.cs, BackgroundScreenPresenter.cs)
- 他の人のジャンプや落下時にエラーログが出ないように修正しました。
  - https://github.com/extreal-dev/Extreal.SampleApp.Holiday.P2P/commit/45b425fe888d37261971407d7182b6d2989fba13 (NetworkManager.prefab)

# 何を確認しましたか?

## 実装
- [x] 実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [x] 静的解析で問題が見つからないことを確認しました

## テスト
- [x] 変更影響がある全てのテストが成功することを確認しました
- [x] 変更影響があるソースのテストカバレッジが100%になることを確認しました

## 変更影響
- [ ] GuideのSample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2024-02-13 12:41 UTC, sus-taguchi-t requested changes

2024-02-13 12:41 UTC, sus-taguchi-t commented on Servers/AppUsage/docker-compose.yaml
> +      test: timeout 20s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
公式の docker-compose.yaml ファイルには以下のように書かれていますが、こちらに合わせた方が良いのではないでしょうか？

```yaml
test: ["CMD", "mc", "ready", "local"]
```

https://github.com/minio/minio/blob/RELEASE.2024-01-29T03-56-32Z/docs/orchestration/docker-compose/docker-compose.yaml

2024-02-13 12:41 UTC, sus-taguchi-t commented on Servers/AppUsage/nginx.conf
ここは何をやっているのでしょうか？

2024-02-14 02:39 UTC, sus-yoshikane-t commented on Servers/AppUsage/docker-compose.yaml
> +      test: timeout 20s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
修正しました。
https://github.com/extreal-dev/Extreal.SampleApp.Holiday.P2P/pull/1/commits/5ff4c392f62dfd40634b8de2def23f9672de3663

2024-02-14 02:43 UTC, sus-yoshikane-t commented on Servers/AppUsage/nginx.conf
CORS対応を行っています。
変更点に[参考リンク](https://dev.azure.com/tixr/xr_fundev/_wiki/wikis/xr_funDev.wiki/1727/fundev%E7%92%B0%E5%A2%83(AWS-EC2)?anchor=cors)を追記しました。

2024-02-19 05:42 UTC, sus-taguchi-t commented on Servers/AppUsage/docker-compose.yaml
> +      test: timeout 20s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
確認しました！

2024-02-19 05:42 UTC, sus-taguchi-t commented on Servers/AppUsage/nginx.conf
確認しました！

2024-02-19 07:00 UTC, sus-taguchi-t approved these changes

2024-02-19 07:00 UTC, merged